apiVersion: v1
kind: ConfigMap
metadata:
  name: linkerd-identity-trust-roots
  namespace: linkerd
data:
  ca-bundle.crt: |
    -----BEGIN CERTIFICATE-----
    MIIBdDCCARugAwIBAgIRALU5EMKDyQlOg7JJoxLfTuEwCgYIKoZIzj0EAwIwGjEY
    MBYGA1UEAxMPaG9tZWxhYi1yb290LWNhMB4XDTI2MDIyMDA3NDExNVoXDTI2MDUy
    MTA3NDExNVowGjEYMBYGA1UEAxMPaG9tZWxhYi1yb290LWNhMFkwEwYHKoZIzj0C
    AQYIKoZIzj0DAQcDQgAEhAYEkewGHxSSkExnriZh0W0c4yR5ht1GKQNQSoFdqhUM
    +0TKWrw0xNCN1in0VpOCtcCcaCO2qv6yUWwsYR2u4aNCMEAwDgYDVR0PAQH/BAQD
    AgKkMA8GA1UdEwEB/wQFMAMBAf8wHQYDVR0OBBYEFIjdilS2fopHnz365bLiGzCe
    nW82MAoGCCqGSM49BAMCA0cAMEQCID3ZAJnALNathGDhyVqVZIW9lVPLjDIrnVOb
    C+svaU/iAiBiFVAHzWCgo2XkG6NyxqSNUdiQE7BPkGz0C7k88FP8vg==
    -----END CERTIFICATE-----
